pip install numpy

In [ ]:
import numpy as np

# **Arrays**


In [ ]:
#Se definen los arrays como np.array([a,b,c])

arr = np.array([1,2,3,4,5])
matrix = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

print('dimensión',matrix.ndim) #ndim permite ver la dimensión del arreglo

#print(arr[desde el idex:hasta antes de index])
#print(matrix[(dim1,dim2 (si hay)),fila,elemento])

for i in matrix:
  print(i)

dimensión 2
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
matrix = np.array([[ [[7,8,9,0],[0,1,2,0]] ], [ [[0,7,8,9],[0,0,1,2]] ], [ [[7,0,8,9],[0,1,0,2]] ]])

print(f'{matrix}\n')
print(f'Número de dimensiones {matrix.ndim}',
      '\nprofundidad1: 1\nprofundidad2: 0\nfila: 1\ncolumna: 2',
      f'\nNúmero encontrado en [1,0,1,2]: {matrix[1,0,1,2]}')

[[[[7 8 9 0]
   [0 1 2 0]]]


 [[[0 7 8 9]
   [0 0 1 2]]]


 [[[7 0 8 9]
   [0 1 0 2]]]]

Número de dimensiones 4 
profundidad1: 1
profundidad2: 0
fila: 1
columna: 2 
Número encontrado en [1,0,1,2]: 1


In [ ]:
#muestra las dimensiones y la cantidad de elementos de cada una
#Va de afuera hacia dentro
print(matrix.shape)
print(np.shape(matrix))

(3, 1, 2, 4)
(3, 1, 2, 4)


In [ ]:
#reordenar la matriz
#debe seguir con la misma cantidad de elementos
reshape_matrix = matrix.reshape(2,3,4,1)
print(reshape_matrix[0])

[[[7]
  [8]
  [9]
  [0]]

 [[0]
  [1]
  [2]
  [0]]

 [[0]
  [7]
  [8]
  [9]]]


In [ ]:
#Iterar en los elementos
#Debe haber la misma cantidad de for que de dimensiones

for dim1 in matrix:
  for dim2 in dim1:
    for row in dim2:
      for element in row:
        print(element)

7
8
9
0
0
1
2
0
0
7
8
9
0
0
1
2
7
0
8
9
0
1
0
2


In [ ]:
#Concatenar arrays
arr1=np.array([[1,2,3],[3,2,1]])
arr2=np.array([[4,5,6],[6,5,4]])

concatenate_axis0 = np.concatenate((arr1, arr2),axis=0)
concatenate_axis1 = np.concatenate((arr1, arr2),axis=1)

print(concatenate_axis0, '\nShape', concatenate_axis0.shape,'\n')
print(concatenate_axis1, '\nShape', concatenate_axis1.shape)

#axis concatena según la dimensión que le pongan empezando por 0

[[1 2 3]
 [3 2 1]
 [4 5 6]
 [6 5 4]] 
Shape (4, 3) 

[[1 2 3 4 5 6]
 [3 2 1 6 5 4]] 
Shape (2, 6)


In [ ]:
#Se reparten los elementos del array de manera uniforme
#array_split
arr=np.array([1,2,1,4,1,6])
print(np.array_split(arr, 2))

[array([1, 2, 1]), array([4, 1, 6])]


In [ ]:
#para buscar la posición de un elemento específico
arr= np.array([1,2,1,4,10,6])
x = np.where(arr == 1)
x

(array([0, 2]),)

In [ ]:
#sort para ordenar

print(np.sort(arr))

[ 1  1  2  4  6 10]
[ 1  1  2  4  6 10]


# **Random**

In [ ]:
from numpy import random

In [ ]:
#randint genera números enteros aleatoreos en un rango específico y puede hacer arreglos de diferentes dimensiones

num = random.randint(5,11, size=(2,3,4))
num

array([[[ 9,  5, 10, 10],
        [ 8,  5,  7,  6],
        [ 6,  8, 10, 10]],

       [[ 5,  8,  6,  9],
        [ 6,  5,  7,  6],
        [ 9,  8,  7,  5]]])

In [ ]:
# rand genera decimales entre el 0 y el 1 y los puede meter en arrays de varias dimensiones desde la exterior hasta la interior
#round permite definir la cantidad de números después de la coma round(num,n) o num.round(n) donde n es es la cantidad de decimales

num_random= random.rand(2,3,10).round(2)
num_random

array([[[0.7 , 0.16, 0.59, 0.14, 0.18, 0.89, 0.27, 0.86, 0.86, 0.75],
        [0.78, 0.52, 0.34, 0.94, 0.38, 0.66, 0.91, 0.67, 0.64, 0.42],
        [0.29, 0.41, 0.64, 0.29, 0.71, 0.57, 0.09, 0.48, 0.6 , 0.5 ]],

       [[0.02, 0.77, 0.09, 0.58, 0.54, 0.59, 0.89, 0.62, 0.79, 0.28],
        [0.  , 0.02, 0.63, 0.34, 0.64, 0.86, 0.2 , 1.  , 0.81, 0.28],
        [0.41, 0.47, 0.42, 0.69, 0.67, 0.28, 0.65, 0.94, 0.54, 0.28]]])

In [ ]:
#random.choice se usa para eligir aleatoriamente o varios números, dento de una cadena y
# hacer un array con los números elegidos de cuantas dimensiones quiera

choices = random.choice(num_random[random.randint(2)][random.randint(3)], size=(3))

for i in choices:
  print('\nNúmeros elegidos', i,'\nPosición en el array',np.where(num_random==i))



Números elegidos 0.94 
Posición en el array (array([0, 1]), array([1, 2]), array([3, 7]))

Números elegidos 0.34 
Posición en el array (array([0, 1]), array([1, 1]), array([2, 3]))

Números elegidos 0.52 
Posición en el array (array([0]), array([1]), array([1]))


# **Otras funciones de numpy**

In [ ]:
print(np.arange(3,10, 3), '-> Números del 3 al 9 en intérvalos de 3 (3,10,3)') #np.arange() Crea un arreglo de números (desde, hasta antes de, cada)

[3 6 9] -> Números del 3 al 9 en intérvalos de 3 (3,10,3)


In [ ]:
#print(np.linspace(2, 10, 5)) #No entiendo el linespace

In [ ]:
print(np.zeros(5)) # devuelve un arreglo lleno de 0
print(np.ones(5)) # devuelve un arreglo lleno de 1

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
print(np.eye(3,4,1)) #crea una matriz de identidad (n filas, n columnas, donde empiezam los 1)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
lista=np.array([1, 2, 3, 4, 5])
print('max',lista.max(), '\nmin',min(lista)) #max() y min() para ver el mayor y el menor elemento de una lista
'index min',lista.argmin()

max 5 
min 1


('index min', 0)

In [ ]:
arr=np.array([5,6,7,8,9])

print(lista, arr)#los 2 arreglos definidos
print(lista - arr)#resta de arreglos elemento por elemento
print(arr + lista)#suma de arreglos elemento por elemento
print(arr + 10)#le suma 10 a cada elemento
print(arr - 10)#le resta 10 a cada elemento
print(arr * 2)#multiplica por 2 cada elemento
print(arr / 2)#divide entre 2 cada elemento

[1 2 3 4 5] [5 6 7 8 9]
[-4 -4 -4 -4 -4]
[ 6  8 10 12 14]
[15 16 17 18 19]
[-5 -4 -3 -2 -1]
[10 12 14 16 18]
[2.5 3.  3.5 4.  4.5]


In [ ]:
print((arr))#arreglo base
print(np.sqrt(arr))#raiz cuadrada de cada elemento
print(np.exp(arr))#arreglo a la e
print(np.sin(arr))#seno de cada elemento
print(np.cos(arr))#coseno de cada elemento
print(np.tan(arr))#tangente de cada elemento
print(np.log(arr))#log en base 10 de cada elemento

[5 6 7 8 9]
[2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
[ 148.4131591   403.42879349 1096.63315843 2980.95798704 8103.08392758]
[-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
[ 0.28366219  0.96017029  0.75390225 -0.14550003 -0.91113026]
[-3.38051501 -0.29100619  0.87144798 -6.79971146 -0.45231566]
[1.60943791 1.79175947 1.94591015 2.07944154 2.19722458]


In [ ]:
arr[:len(arr)] #Muestra los elementos (desde: hasta antes del)

array([5, 6, 7, 8, 9])

In [ ]:
new_arr = arr.copy() #.copy() sirve para copiar un arreglo y ponerlo en otro
new_arr

array([5, 6, 7, 8, 9])

In [ ]:
print(arr % 2 == 0) #Hacer un condicional con los valores del arreglo que devuelve False o true según la condición y el elemento

print(arr[arr % 2 == 1]) #Devuelve un arreglo con los elemmentos que cumplen con la condición

[False  True False  True False]
[5 7 9]


In [ ]:
print('\nMatriz de dimensión 1 \n',np.array([1,2,3,4]) ,'\n________________________')
print('\nMatriz de dimensión 2 \n',np.array([[1,2,3,4],[5,6,7,8]]) ,'\n________________________')
print('\nMatriz de dimensión 3 \n',np.array([[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[5,6,7,8]]]) ,'\n________________________')
print('\nMatriz de dimensión 4 \n',np.array([[[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[5,6,7,8]]],[[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[5,6,7,8]]]]) ,'\n________________________')



Matriz de dimensión 1 
 [1 2 3 4] 
________________________

Matriz de dimensión 2 
 [[1 2 3 4]
 [5 6 7 8]] 
________________________

Matriz de dimensión 3 
 [[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]] 
________________________

Matriz de dimensión 4 
 [[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]


 [[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]] 
________________________


In [ ]:
import numpy as np

def calculate(list):
    if len(list) != 9:
        raise ValueError("List must contain nine numbers.")

    else:
        list = np.array(list).reshape(3,3)
        t_list = np.transpose(list)
        calculations = {
            'mean': [[np.mean(t_list[0]), np.mean(t_list[1]), np.mean(t_list[2])], [np.mean(list[0]), np.mean(list[1]), np.mean(list[2])], np.mean(list)],
            'variance': [[np.var(t_list[0]), np.var(t_list[1]), np.var(t_list[2])], [np.var(list[0]), np.var(list[1]), np.var(list[2])], np.var(list)],
            'standard deviation': [[np.std(t_list[0]), np.std(t_list[1]), np.std(t_list[2])], [np.std(list[0]), np.std(list[1]), np.std(list[2])], np.std(list)],
            'max': [[np.max(t_list[0]), np.max(t_list[1]), np.max(t_list[2])], [np.max(list[0]), np.max(list[1]), np.max(list[2])], np.max(list)],
            'min': [[np.min(t_list[0]), np.min(t_list[1]), np.min(t_list[2])], [np.min(list[0]), np.min(list[1]), np.min(list[2])], np.min(list)],
            'sum': [[np.sum(t_list[0]), np.sum(t_list[1]), np.sum(t_list[2])], [np.sum(list[0]), np.sum(list[1]), np.sum(list[2])], np.sum(list)]
        }
    return calculations

In [ ]:
calculate([2,6,2,8,4,0,1,5,7])

{'mean': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889],
 'variance': [[9.555555555555557, 0.6666666666666666, 8.666666666666666],
  [3.555555555555556, 10.666666666666666, 6.222222222222221],
  6.987654320987654],
 'standard deviation': [[3.091206165165235,
   0.816496580927726,
   2.943920288775949],
  [1.8856180831641267, 3.265986323710904, 2.494438257849294],
  2.6434171674156266],
 'max': [[8, 6, 7], [6, 8, 7], 8],
 'min': [[1, 4, 0], [2, 0, 1], 0],
 'sum': [[11, 15, 9], [10, 12, 13], 35]}